.travis.yml:
  sudo: true
  dist: trusty
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE=small
      # Integration test matrix
      #
      # Mesos releases occur every two months, and each minor release is supported for six months.
      # For more info, see: http://mesos.apache.org/documentation/latest/versioning/
      #
      # Fortunately, Mesosphere doesn't remove previous releases from its Apt repositories.
      # Determine the version string to use here by running `apt-get update && apt-cache policy mesos`
      - TEST_TYPE=medium MESOS_RELEASE=0.28.1-2.0.20.ubuntu1404
      - TEST_TYPE=medium MESOS_RELEASE=0.27.2-2.0.15.ubuntu1404
      - TEST_TYPE=medium MESOS_RELEASE=0.26.1-2.0.19.ubuntu1404
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: jf60Yk6AZx57R2nNRzNdfHavImhm9ZddI4BOjcmdHrYCnHKSKxRpgslOle2rRiJU6ioXtVao8hfNxT/VSW3LUgZZQYOyL3RmxVB+G7ywZsIj8k9mZ6Te45l0vO1tFUV6vMm3j2/owKkoyQZo2465WZSnd4jay2/lxd1vhOoAkiMuit10hLnvlYFbbzePpwSkLqiT354DZz29fHdTK8AeBS4dtgj7QtAi/HZJWKXg8yKt3A9qtsjYQKyyulxp9UKZ+hbg6RFj7HxHf3bbW7pY/BgQhGOE78crrYaODtc4J/2Uw3CVe41SpNmK3sPI8GKBiIf6QOtbEhZlJydnjwQT1yBnrCGEZlE8xNGLMtQpXzgQzAwfM98imLzvW3sz5IlqDzKj5QRxzQqKOJoPt77wBY0hG6xnqa85EvKUM46f6jTtgp36zoUTus11nBbi7HgzOxVc760IKVdV6vOuJ5G/yiOMFl5CAQpSx3aodWz4ARFCA0g5x7p1qG/dlodGhP8n/CuUjDNBL5ox8DQhcU2X71Cffz0vdYpQQxKFNKvGM5mIILbSNp2t+XlFDUabi4Hv2jr1ZCAIrtGMB4fX6zvpVXlmUhI+XmZ/F6rxLDAst+EjI5HwGJUyKk5EdB8r7T6LWp982LN4K/FjzKtCnVgnO0EZAB/vqlNmJdLBw2C0gRo=
    api_key:
      secure: nkqx/GycwAJRKk5qKVENDuHPTYdQ6rsAzFEXSeHLxg7QuxJcWfwexbL5oJHkNnuj0Qg3udLRuEUkLrS1eMIIQUhjVeVliN6m+wg2rzn8PGgV57NX4HMA3iLBHZzf1lbuD5XsAsFVM2xvOycjCwhz8sncedhcE06O23Lwc8++uaXIRjiajYAwghlVA3i8DEwyhc1KI5bjOKmr6aWsYhvQkXrGw/5Wqk6hJkTELxmO9n7l6qEQfaKTTgdM8L94jE0DdQQmIGPhsq7iKw+5dfBWMsM3krVniBk56xOTKXPG4tdN0cgAtrne59LKL84ySj6IMOHZQWBXipsZwdljf02Njbz+cong3AlkEOKChK7hRbcDmoGpyOnScPKOAk8dQOvGiWRe9lXK2VDhzPZA7imBm2Z1kiORtpBGxtOD8HC41snr7gejYIGwWbpU0tLMImoS85pZuccRNJeZM7b+BHAUMIpXPKDh5F/Zv1t6B5ZgYmF/IQmOyz9DTNKwWZ8FjeX/ASZN3/Ty3bFxJCQ5pAtVg1ZcLt9EIcLoWKjjkvuc3GEwOdBRzcoDC7fK5hP+uw4o/Qoi7zq1TO/zKH84pSc8K1m3ORiV2sMGEb5ojVakJwXak9LZF8UHh5HeupF5xE4CEyZVZ2/zLDTMoBXv+uAEvo6DwGw8BnxX8yLX+zZeLGU=
