language: go

go:
  - 1.5.4
  - 1.6.2

env:
  global:
    - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/intelsdi-x/snap-plugin-collector-mesos
  matrix:
    - TEST=unit

before_install:
  - go get github.com/tools/godep
  - go get github.com/intelsdi-x/snap
  - if [ ! -d $SNAP_PLUGIN_SOURCE ]; then mkdir -p $HOME/gopath/src/github.com/intelsdi-x; ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE; fi # CI for forks not from intelsdi-x

install:
  - export TMPDIR=$HOME/tmp
  - mkdir -p $TMPDIR
  - cd $SNAP_PLUGIN_SOURCE
  - make deps

script:
  - make check TEST=$TEST 2>&1
