language: go
sudo: required
dist: trusty

go:
  - 1.5.4
  - 1.6.2

env:
  global:
    - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/intelsdi-x/snap-plugin-collector-mesos
  matrix:
    # Unit test matrix
    - TEST=unit

    # Integration test matrix
    #
    # Mesos releases occur every two months, and each minor release is supported for six months.
    # For more info, see: http://mesos.apache.org/documentation/latest/versioning/
    #
    # Fortunately, Mesosphere doesn't remove previous releases from its Apt repositories.
    # Determine the version string to use here by running `apt-get update && apt-cache policy mesos`
    - TEST=integration MESOS_RELEASE=0.28.1-2.0.20.ubuntu1404
    - TEST=integration MESOS_RELEASE=0.27.2-2.0.15.ubuntu1404
    - TEST=integration MESOS_RELEASE=0.26.1-2.0.19.ubuntu1404

before_install:
  - go get github.com/tools/godep
  - if [ ! -d $SNAP_PLUGIN_SOURCE ]; then mkdir -p $HOME/gopath/src/github.com/intelsdi-x; ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE; fi # CI for forks not from intelsdi-x

install:
  - export TMPDIR=$HOME/tmp
  - mkdir -p $TMPDIR
  - cd $SNAP_PLUGIN_SOURCE
  - make deps

script:
  - make check TEST=$TEST 2>&1
